-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    website TEXT,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE
    IF EXISTS public.companies OWNER TO postgres;

ALTER TABLE
    IF EXISTS public.companies ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON ALL TABLES IN SCHEMA "public" TO authenticated;

CREATE POLICY "Authenticated users can access table data" ON public.companies FOR
SELECT
    USING (true);

CREATE POLICY "Admin users can update table data" ON public.companies FOR
UPDATE
    USING (
        auth.uid() IN (
            SELECT
                id
            FROM
                public.users
            WHERE
                role = 'admin'
        )
    );

CREATE POLICY "Admin users can insert table data" ON public.companies FOR
INSERT
    WITH CHECK (
        auth.uid() IN (
            SELECT
                id
            FROM
                public.users
            WHERE
                role = 'admin'
        )
    );
